Add tests for `Ellipsoid` and `Hexahedron`
mikeingold/MeshIntegrals.jl pull request #102
Opened 2024-10-09 15:22 UTC by JoshuaLampert

Integrating `Ellipsoid` and `Hexahedron` should simply work. However, I needed to set pretty high tolerances for `Ellipsoid` for some reason. Do you know why @mikeingold?
I also added other geometries, which do not implement any parametric function yet, in the support matrix, cf. #57

2024-10-09 15:23 UTC, JoshuaLampert commented
Just as a note: The link behind the 🎗️ in the docs doesn't seem to work.

2024-10-09 15:44 UTC, JoshuaLampert commented
> However, I needed to set pretty high tolerances for `Ellipsoid` for some reason. Do you know why @mikeingold?

Ah, I see why. The result of `measure` is already off by the tolerance because Meshes.jl doesn't implement an analytical  `measure` for an `Ellipsoid` (which is also not so easy to determine in general) and thus uses a [fallback](https://github.com/JuliaGeometry/Meshes.jl/blob/994b30a17c830a7d9f576af90b252e717dfc0fcb/src/measures.jl#L112).

```julia
julia> using Meshes, MeshIntegrals

julia> origin = Point(0, 0, 0)
Point with Cartesian{NoDatum} coordinates
├─ x: 0.0 m
├─ y: 0.0 m
└─ z: 0.0 m

julia> radii = (1.0, 1.0, 1.0)
(1.0, 1.0, 1.0)

julia> ellipsoid = Ellipsoid(radii, origin)
Ellipsoid
├─ radii: (1.0 m, 1.0 m, 1.0 m)
├─ center: Point(x: 0.0 m, y: 0.0 m, z: 0.0 m)
└─ rotation: LinearAlgebra.UniformScaling{Bool}(true)

julia> using Unitful: m

julia> 4pi*m^2 - measure(ellipsoid)
0.02225157793214194 m^2

julia> 4pi*m^2 - integral(f, ellipsoid, GaussLegendre(100))
-4.96278573791642e-11 m^2
```

The result from `integral` is actually much more precise.

2024-10-09 17:01 UTC, mikeingold commented
> Ah, I see why. The result of `measure` is already off by the tolerance because Meshes.jl doesn't implement an analytical  `measure` for an `Ellipsoid` (which is also not so easy to determine in general) and thus uses a [fallback](https://github.com/JuliaGeometry/Meshes.jl/blob/994b30a17c830a7d9f576af90b252e717dfc0fcb/src/measures.jl#L112).
> 
> The result from `integral` is actually much more precise.

Exactly. This is something I've definitely seen. When there's no analytic solution defined for measure, Meshes will `simplexify` the geometry and essentially take a finite element approximation, so integrating a unit integrand function will probably be more accurate. This is one of the motivations behind moving away from the old auto tests that relied on measure as a benchmark.

2024-10-09 19:58 UTC, mikeingold commented
> Just as a note: The link behind the 🎗️ in the docs doesn't seem to work.

Weird. It looks like the Documenter site's `stable` version is stale and
hasn't been updated since ~v13.2. The pages under `dev` are up to date,
though. Have you ever seen this kind of thing happen before?

On Wed, Oct 9, 2024 at 1:04 PM Joshua Lampert ***@***.***>
wrote:

> Once the overall goal to test against analytical solutions is achieved in
> the future, we will not depend on measure anyway.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mikeingold/MeshIntegrals.jl/pull/102#issuecomment-2402853954>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA657OWQVEMHK4B7RCK6HKDZ2VOYHAVCNFSM6AAAAABPUZPOG6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBSHA2TGOJVGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-09 20:07 UTC, JoshuaLampert commented
> Weird. It looks like the Documenter site's `stable` version is stale and
hasn't been updated since ~v13.2. The pages under `dev` are up to date,
though. Have you ever seen this kind of thing happen before?

Indeed. I don't know why this is and I don't see any suspicious in the logs.

2024-10-10 03:10 UTC, mikeingold requested changes

2024-10-10 03:12 UTC, mikeingold commented
> > Weird. It looks like the Documenter site's `stable` version is stale and
> > hasn't been updated since ~v13.2. The pages under `dev` are up to date,
> > though. Have you ever seen this kind of thing happen before?
> 
> Indeed. I don't know why this is and I don't see anything suspicious in the logs.

We don't have to hold up this PR over it. I just added #103 for tracking.

2024-10-10 06:52 UTC, JoshuaLampert commented on docs/src/supportmatrix.md
I pushed two commits addressing these points.

2024-10-10 10:55 UTC, mikeingold approved these changes

2024-10-10 10:56 UTC, merged