Add an extended tag for time-intensive unit tests
mikeingold/MeshIntegrals.jl pull request #109
Opened 2024-10-14 20:02 UTC by mikeingold

2024-10-14 20:16 UTC, mikeingold commented
We're down to <10 minute CI times just by pushing two geometry types into `:extended` test sets. 😃

2024-10-14 21:25 UTC, JoshuaLampert requested changes
Could we put the test for a wrong number of parametric coordinates into another `@testitem` to keep at least that one covered? It currently is in the 4D Box test (lines 199-200), but could also live somewhere else.

2024-10-14 21:47 UTC, mikeingold commented
Good catch! I just moved it from 4D to 2D

2024-10-15 07:44 UTC, JoshuaLampert approved these changes
Thanks!

2024-10-15 09:59 UTC, merged